/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppResearchRouteImport } from './routes/_app.research'
import { Route as AppMeetingRouteImport } from './routes/_app.meeting'
import { Route as AppEmailRouteImport } from './routes/_app.email'
import { Route as AppChatbotRouteImport } from './routes/_app.chatbot'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingRoute = AppMeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/chatbot': typeof AppChatbotRoute
  '/email': typeof AppEmailRoute
  '/meeting': typeof AppMeetingRoute
  '/research': typeof AppResearchRoute
  '/tasks': typeof AppTasksRoute
}
export interface FileRoutesByTo {
  '/chatbot': typeof AppChatbotRoute
  '/email': typeof AppEmailRoute
  '/meeting': typeof AppMeetingRoute
  '/research': typeof AppResearchRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/chatbot': typeof AppChatbotRoute
  '/_app/email': typeof AppEmailRoute
  '/_app/meeting': typeof AppMeetingRoute
  '/_app/research': typeof AppResearchRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chatbot' | '/email' | '/meeting' | '/research' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/chatbot' | '/email' | '/meeting' | '/research' | '/tasks' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/chatbot'
    | '/_app/email'
    | '/_app/meeting'
    | '/_app/research'
    | '/_app/tasks'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meeting': {
      id: '/_app/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof AppMeetingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email': {
      id: '/_app/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatbotRoute: typeof AppChatbotRoute
  AppEmailRoute: typeof AppEmailRoute
  AppMeetingRoute: typeof AppMeetingRoute
  AppResearchRoute: typeof AppResearchRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatbotRoute: AppChatbotRoute,
  AppEmailRoute: AppEmailRoute,
  AppMeetingRoute: AppMeetingRoute,
  AppResearchRoute: AppResearchRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
